backend:
  name: github
  repo: "sofievergauwe/sofievergauwe.be"
  branch: master


media_folder: "/media/"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2"}
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Layout", name: "layout", widget: "select", required: false, options: ["page", "frontpage"], default: "page" }
      - {label: "Body", name: "body", widget: "markdown"}
