backend:
  name: git-gateway

media_folder: "media" # Folder where user uploaded files should go
public_folder: "media"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
