backend:
  name: github
  repo: "sofievergauwe/sofievergauwe.be"
  branch: master


media_folder: "/media/"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h2" }
      - {label: "Permalink", name: "permalink", widget: "string" }
      - {label: "Layout", name: "layout", widget: "hidden", required: true, default: "page" }
      - {label: "Image", name: "image", widget: "image", required: false }
      - label: "Caption"
        name: caption
        required: false
        widget: "object"
        fields:
          - {label: "Quote", name: "quote", widget: "string" }
          - {label: "Cite", name: "cite", widget: "string" }
          - {label: "Vertical align", name: "vertical-align", widget: "select", required: true, options: ["top", "middle", "bottom"], default: "middle" }
          - {label: "Horizontal align", name: "Horizontal-align", widget: "select", required: true, options: ["left", "center", "right"], default: "center" }
      - {label: "Body", name: "body", widget: "markdown" }
      - label: "Information"
        name: info
        required: false
        widget: "object"
        fields:
          - {label: "Image", name: "image", widget: "image", required: false }
          - {label: "Description", name: "description", widget: "markdown" }
          - label: "Prices"
            name: prices
            required: false
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Time", name: "time", widget: "string"}
              - {label: "Price", name: "price", widget: "string"}

  - name: "menu"
    label: "Menu"
    editor:
      preview: false
    files:
      - name: "mainmenu"
        label: "Mainmenu"
        file: "_data/menu.yml"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
