backend:
  name: github
  repo: "sofievergauwe/sofievergauwe.be"
  branch: master


media_folder: "/media/"

collections:

  - name: "frontpage"
    label: "Frontpage"
    folder: "_pages"
    filter:
      field: layout
      value: frontpage
    create: false
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Link", name: "permalink", widget: "string" }
      - {label: "Layout", name: "layout", widget: "hidden", required: true, default: "frontpage" }
      - {label: "Banner", name: "image", widget: "image", required: false }
      - label: "Banner caption"
        name: caption
        required: false
        widget: "object"
        fields:
          - {label: "Quote", name: "quote", widget: "string" }
          - {label: "Cite", name: "cite", widget: "string" }
          - {label: "Vertical align", name: "vertical-align", widget: "select", required: true, options: ["top", "middle", "bottom"], default: "middle" }
          - {label: "Horizontal align", name: "horizontal-align", widget: "select", required: true, options: ["left", "center", "right"], default: "center" }
      - name: teasers
        label: Teasers
        widget: list
        fields:
          - {label: "Title", name: "title", widget: "string" }
          - {label: "Image", name: "image", widget: "image" }
          - {label: "Link", name: "link", widget: "string", required: false}
          - {label: "Description", name: "description", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "_pages"
    filter:
      field: layout
      value: page
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string" }
      - {label: "Link", name: "permalink", widget: "string" }
      - {label: "Layout", name: "layout", widget: "hidden", required: true, default: "page" }
      - {label: "Banner", name: "image", widget: "image", required: false }
      - label: "Banner caption"
        name: caption
        required: false
        widget: "object"
        fields:
          - {label: "Quote", name: "quote", widget: "string", required: false }
          - {label: "Cite", name: "cite", widget: "string", required: false }
          - {label: "Vertical align", name: "vertical-align", widget: "select", required: true, options: ["top", "middle", "bottom"], default: "middle" }
          - {label: "Horizontal align", name: "horizontal-align", widget: "select", required: true, options: ["left", "center", "right"], default: "center" }
      - {label: "Body", name: "body", widget: "markdown" }
      - label: "Info"
        name: info
        required: false
        widget: object
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - {label: "Image", name: "image", widget: "image", required: false }
          - {label: "Description", name: "description", widget: "markdown", required: false }
      - label: "Datalist"
        name: datalist
        required: false
        widget: object
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - {label: "Description", name: "description", widget: "markdown", required: false }
          - label: "Items"
            name: items
            required: false
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Info", name: "info", widget: "string"}
              - {label: "Data", name: "data", widget: "string"}
      - label: "Links"
        name: links
        required: false
        widget: object
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - {label: "Description", name: "description", widget: "markdown", required: false }
          - label: "Items"
            name: items
            required: false
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string" }
              - {label: "Url", name: "url", widget: "string" }
      - label: "Buttons"
        name: buttons
        required: false
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string" }
          - {label: "Url", name: "url", widget: "string" }

  - name: "forms"
    label: "Forms"
    editor:
      preview: false
    folder: "_forms"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Success link", name: "success", widget: "string"}
      - label: "Fields"
        name: fields
        widget: "list"
        fields:
          - {label: "Name", name: name, widget: string}
          - {label: "Label", name: label, widget: string}
          - {label: "Type", name: "type", widget: "select", options: ["text", "textarea", "email", "number", "file"], default: "text" }
          - {label: "Required", name: "required", widget: "boolean", default: false}
          - {label: "Options", name: options, widget: "list", required: false}

  - name: "site"
    label: "Site"
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "_data/menu.yml"
        fields:
          - {label: "Title", name: "title", widget: "string" }
          - name: links
            label: Links
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Icon", name: "icon", widget: "select", options: ["", "facebook", "instagram"], default: "" }
      - name: "info"
        label: "Info"
        file: "_data/info.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", required: false }
          - {label: "Name", name: "name", widget: "string", required: false }
          - {label: "Street", name: "street", widget: "string", required: false }
          - {label: "Postal", name: "postal", widget: "string", required: false }
          - {label: "Locality", name: "locality", widget: "string", required: false }
          - {label: "Phone", name: "tel", widget: "string", required: false }
          - {label: "Mobile", name: "mobile", widget: "string", required: false }
          - {label: "Email", name: "email", widget: "string", required: false }
