backend:
  name: git-gateway
  branch: master

media_folder: "media"

collections:
  - name: "pages"
    label: "Page"
    folder: "_pages"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
